-- MySQL Script generated by MySQL Workbench
-- vie 31 jul 2015 20:04:11 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tweetgrill
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tweetgrill
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweetgrill` DEFAULT CHARACTER SET utf8 ;
USE `tweetgrill` ;

-- -----------------------------------------------------
-- Table `tweetgrill`.`grill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweetgrill`.`grill` (
  `id_grill` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `unique_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(22) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `secret` VARCHAR(25) NOT NULL,
  `published` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_grill`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tweetgrill`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweetgrill`.`tweet` (
  `id_tweet` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `published` ENUM('0', '1') NOT NULL DEFAULT '1',
  `order` INT NOT NULL DEFAULT 0,
  `id_grill` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_tweet`) ,
  INDEX `fk_tweet_grill_idx` (`id_grill` ASC) ,
  CONSTRAINT `fk_tweet_grill`
    FOREIGN KEY (`id_grill`)
    REFERENCES `tweetgrill`.`grill` (`id_grill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
